[package]
name = "advent2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils = { git = "https://github.com/cglosser/advent_utils", branch = "main" }
clap = "2.33"
itertools = "0.10"
lazy_static = "1.4"
md5 = "0.7"
regex = "1.5"